//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookYear", ReplyAction="*")]
        Client.ServiceReference1.BookYearResponse BookYear(Client.ServiceReference1.BookYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookYear", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.BookYearResponse> BookYearAsync(Client.ServiceReference1.BookYearRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookYear", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.BookYearRequestBody Body;
        
        public BookYearRequest() {
        }
        
        public BookYearRequest(Client.ServiceReference1.BookYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Book book;
        
        public BookYearRequestBody() {
        }
        
        public BookYearRequestBody(Client.ServiceReference1.Book book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookYearResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.BookYearResponseBody Body;
        
        public BookYearResponse() {
        }
        
        public BookYearResponse(Client.ServiceReference1.BookYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookYearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int BookYearResult;
        
        public BookYearResponseBody() {
        }
        
        public BookYearResponseBody(int BookYearResult) {
            this.BookYearResult = BookYearResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Client.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ServiceSoap>, Client.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.BookYearResponse Client.ServiceReference1.ServiceSoap.BookYear(Client.ServiceReference1.BookYearRequest request) {
            return base.Channel.BookYear(request);
        }
        
        public int BookYear(Client.ServiceReference1.Book book) {
            Client.ServiceReference1.BookYearRequest inValue = new Client.ServiceReference1.BookYearRequest();
            inValue.Body = new Client.ServiceReference1.BookYearRequestBody();
            inValue.Body.book = book;
            Client.ServiceReference1.BookYearResponse retVal = ((Client.ServiceReference1.ServiceSoap)(this)).BookYear(inValue);
            return retVal.Body.BookYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.BookYearResponse> Client.ServiceReference1.ServiceSoap.BookYearAsync(Client.ServiceReference1.BookYearRequest request) {
            return base.Channel.BookYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.BookYearResponse> BookYearAsync(Client.ServiceReference1.Book book) {
            Client.ServiceReference1.BookYearRequest inValue = new Client.ServiceReference1.BookYearRequest();
            inValue.Body = new Client.ServiceReference1.BookYearRequestBody();
            inValue.Body.book = book;
            return ((Client.ServiceReference1.ServiceSoap)(this)).BookYearAsync(inValue);
        }
    }
}
